version: "3.9"
services:
  postgres:
    container_name: db_bt_api
    image: "postgres:14-alpine"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Root
      POSTGRES_DB: bt_api
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - mynet
  apiserver:
    container_name: bt_api
    build: .
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - mynet
    ports:
      - 8080:8080  
  
volumes:
  api:
  database_postgres:  

networks:
  mynet:
    driver: bridge  